name: Run Blocket Facebook Bot

on:
  schedule:
    - cron: '*/10 * * * *'  # Var 10:e minut
  workflow_dispatch:  # Kan köras manuellt

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run bot script
      env:
        BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
        CHAT_ID: ${{ secrets.CHAT_ID }}
        APIFY_TOKEN: ${{ secrets.APIFY_TOKEN }}
      run: python main.py
